name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  # CI
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test

  # CD
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/tscadmin/tscadmin/cicd-node-server
            git pull
            git status
            nvm use 18
            yarn install
            yarn build
            pm2 restart cicd-node-server
